services:
  sealbot:
    image:  ghcr.io/n0201/public_sealbot:main
    container_name: sealbot
    restart: unless-stopped
    environment:
      - SEALBOT_SECRET=
      - SEALBOT_UPDATE_CHATID=
      - SEALBOT_ADMINS=
    volumes:
      - ./pictures:/app/pictures
      - ./ota:/app/ota
