name: Build and Push to Docker Hub on changes to main branch

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}} # needs read:packages, write:packages. delete:packages


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}/:main
            ${{ github.repository }}/:latest
            ${{ github.repository }}/:commit-${{ github.sha }}

      - name: Send POST Request to deploy changes
        run: |
          curl -X POST ${{ secrets.DEPLOY_URL }}          


